name: cat_breed
description: "The CatBreed is a simple web application that allows users to search for cat breeds and view their details. "
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.2
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  fpdart: ^1.1.1
  get_it: ^8.0.3
  go_router: ^15.1.2
  shimmer: ^3.0.0
  stream_transform: ^2.1.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.0
  test: ^1.24.0
  build_runner: ^2.4.0
  import_sorter: ^4.6.0
  mutation_test: ^1.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
